# Generated by Django 4.0.5 on 2023-04-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_remove_curso_entregables_curso_entregables'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='fecha_inicio',
            field=models.DateField(null=True),
        ),
    ]
